package com.rankmonkeysvc.constants;

public enum ErrorTitle {
    USER_NOT_FOUND,
	BAD_CREDENTIALS,
	DUPLICATE_EMAIL,
	INVALID_EMAIL_FORMAT,
	DATABASE_OPERATION_FAILED,
	MAXIMUM_RETRY_COUNT_EXCEEDED,
	LINK_HAS_EXPIRED,
	INVALID_EMAIL,
	INVALID_TOKEN,
	INVALID_PASSWORD,
	REFRESH_TOKEN_EXPIRED,
	NEW_AND_OLD_PASSWORD_CANNOT_BE_SAME,
	UNAUTHORIZED_ENDPOINT,
	DUPLICATE_JOB_ROLE,
	INVALID_REQUEST,
}