package com.rankmonkeysvc.constants;

public enum QuestionType {
    SINGLE_SELECT_MCQ,
    MULTI_SELECT_MCQ,
    SUBJECTIVE,
    CODING,
    TRUE_FALSE,
    SHORT_ANSWER,
    PROJECT_CASE_STUDY,
    ALGORITHM_DESIGN,
    ESSAY,
    DRAG_AND_DROP,
    DIAGRAM_FLOWCHART,
    PEER_REVIEW,
    GAMIFIED,
    CASE_BASED_MCQ,
    VIDEO_AUDIO_RESPONSE,
    PAIR_PROGRAMMING,
    TIMED_QUIZ,
    PROBLEM_DIAGNOSIS,
    ROLE_BASED_TASKS,
    DATA_INTERPRETATION,
    LOGICAL_REASONING,
    SCENARIO_BASED,
    SOFT_SKILLS
}