server:
  port: 9999
  shutdown: immediate

debug: false

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
      mongodb:
        driver: INFO
      postgresql:
        Driver: INFO
        jdbc: INFO
      apache:
        catalina: INFO
    com:
      zaxxer:
        hikari: INFO

app:
  cors:
    allowed-origins:
  config:
    connectifysvc: ""
    projectmgmtsvc: ""

spring:
  data:
    mongodb:
      uri: "mongodb+srv://dipankarbhaduri8:dipankarbhaduri8@cluster0.tnvgzpi.mongodb.net/event-pilot?retryWrites=true&w=majority"
      connection-pool-size: 10
      socket-timeout: 2000
  #  kafka:
  #    producer:
  #      event-topic:
  #      bootstrap-servers:
  #  redis:
  #    host: ${REDIS_HOST}
  #    port: 6379
  #    password: ${REDIS_PASSWORD}
  profiles:
    active: local
  #  servlet:
  #    multipart:
  #      max-file-size: 5MB
  #      max-request-size: 5MB
  #  security:
  #    user:
  #      name: local
  #      password: local
  #    oauth2:
  #      client:
  #        registration:
  #          google:
  #            client-id: ${GOOGLE_CLIENT_ID}
  #            client-secret: ${GOOGLE_CLIENT_SECRET}
  #            scope: openid,profile,email
  #            authorization-grant-type: authorization_code
  #            redirect-uri: "http://localhost:3000"
  #      resourceserver:
  #        jwt:
  #          issuer-uri: accounts.google.com
  #          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
#      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg-4b157ca-country-state-pincode.l.aivencloud.com:12827/defaultdb
    username: avnadmin
    password: AVNS_yDWtELnIM9VVAzt6qbx